/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FdfdService } from "../fdfd.service";
import { FdfdCreateInput } from "./FdfdCreateInput";
import { Fdfd } from "./Fdfd";
import { FdfdFindManyArgs } from "./FdfdFindManyArgs";
import { FdfdWhereUniqueInput } from "./FdfdWhereUniqueInput";
import { FdfdUpdateInput } from "./FdfdUpdateInput";

export class FdfdControllerBase {
  constructor(protected readonly service: FdfdService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Fdfd })
  async createFdfd(@common.Body() data: FdfdCreateInput): Promise<Fdfd> {
    return await this.service.createFdfd({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Fdfd] })
  @ApiNestedQuery(FdfdFindManyArgs)
  async fdfds(@common.Req() request: Request): Promise<Fdfd[]> {
    const args = plainToClass(FdfdFindManyArgs, request.query);
    return this.service.fdfds({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Fdfd })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fdfd(
    @common.Param() params: FdfdWhereUniqueInput
  ): Promise<Fdfd | null> {
    const result = await this.service.fdfd({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Fdfd })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFdfd(
    @common.Param() params: FdfdWhereUniqueInput,
    @common.Body() data: FdfdUpdateInput
  ): Promise<Fdfd | null> {
    try {
      return await this.service.updateFdfd({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Fdfd })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFdfd(
    @common.Param() params: FdfdWhereUniqueInput
  ): Promise<Fdfd | null> {
    try {
      return await this.service.deleteFdfd({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
