import { AccountUpdateManyWithoutUsersInput } from "./AccountUpdateManyWithoutUsersInput";
import { ApiKeyUpdateManyWithoutUsersInput } from "./ApiKeyUpdateManyWithoutUsersInput";
import { AvailabilityUpdateManyWithoutUsersInput } from "./AvailabilityUpdateManyWithoutUsersInput";
import { BookingUpdateManyWithoutUsersInput } from "./BookingUpdateManyWithoutUsersInput";
import { CredentialUpdateManyWithoutUsersInput } from "./CredentialUpdateManyWithoutUsersInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { EventTypeUpdateManyWithoutUsersInput } from "./EventTypeUpdateManyWithoutUsersInput";
import { FeedbackUpdateManyWithoutUsersInput } from "./FeedbackUpdateManyWithoutUsersInput";
import { ImpersonationUpdateManyWithoutUsersInput } from "./ImpersonationUpdateManyWithoutUsersInput";
import { InputJsonValue } from "../../types";
import { ScheduleUpdateManyWithoutUsersInput } from "./ScheduleUpdateManyWithoutUsersInput";
import { SelectedCalendarUpdateManyWithoutUsersInput } from "./SelectedCalendarUpdateManyWithoutUsersInput";
import { SessionUpdateManyWithoutUsersInput } from "./SessionUpdateManyWithoutUsersInput";
import { MembershipUpdateManyWithoutUsersInput } from "./MembershipUpdateManyWithoutUsersInput";
import { WebhookUpdateManyWithoutUsersInput } from "./WebhookUpdateManyWithoutUsersInput";
import { WorkflowUpdateManyWithoutUsersInput } from "./WorkflowUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  accounts?: AccountUpdateManyWithoutUsersInput;
  allowDynamicBooking?: boolean | null;
  apiKeys?: ApiKeyUpdateManyWithoutUsersInput;
  availability?: AvailabilityUpdateManyWithoutUsersInput;
  avatar?: string | null;
  away?: boolean;
  bio?: string | null;
  bookings?: BookingUpdateManyWithoutUsersInput;
  brandColor?: string;
  bufferTime?: number;
  completedOnboarding?: boolean;
  credentials?: CredentialUpdateManyWithoutUsersInput;
  darkBrandColor?: string;
  defaultScheduleId?: number | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableImpersonation?: boolean;
  email?: string;
  emailVerified?: Date | null;
  endTime?: number;
  eventTypes?: EventTypeUpdateManyWithoutUsersInput;
  feedback?: FeedbackUpdateManyWithoutUsersInput;
  hideBranding?: boolean;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: string | null;
  impersonatedBy?: ImpersonationUpdateManyWithoutUsersInput;
  impersonatedUsers?: ImpersonationUpdateManyWithoutUsersInput;
  invitedTo?: number | null;
  locale?: string | null;
  metadata?: InputJsonValue;
  name?: string | null;
  password?: string | null;
  plan?: "FREE" | "TRIAL" | "PRO";
  role?: "USER" | "ADMIN";
  schedules?: ScheduleUpdateManyWithoutUsersInput;
  selectedCalendars?: SelectedCalendarUpdateManyWithoutUsersInput;
  sessions?: SessionUpdateManyWithoutUsersInput;
  startTime?: number;
  teams?: MembershipUpdateManyWithoutUsersInput;
  theme?: string | null;
  timeFormat?: number | null;
  timeZone?: string;
  trialEndsAt?: Date | null;
  twoFactorEnabled?: boolean;
  twoFactorSecret?: string | null;
  username?: string | null;
  verified?: boolean | null;
  webhooks?: WebhookUpdateManyWithoutUsersInput;
  weekStart?: string;
  workflows?: WorkflowUpdateManyWithoutUsersInput;
};
