import { Account } from "../account/Account";
import { ApiKey } from "../apiKey/ApiKey";
import { Availability } from "../availability/Availability";
import { Booking } from "../booking/Booking";
import { Credential } from "../credential/Credential";
import { DestinationCalendar } from "../destinationCalendar/DestinationCalendar";
import { EventType } from "../eventType/EventType";
import { Feedback } from "../feedback/Feedback";
import { Impersonation } from "../impersonation/Impersonation";
import { JsonValue } from "type-fest";
import { Schedule } from "../schedule/Schedule";
import { SelectedCalendar } from "../selectedCalendar/SelectedCalendar";
import { Session } from "../session/Session";
import { Membership } from "../membership/Membership";
import { Webhook } from "../webhook/Webhook";
import { Workflow } from "../workflow/Workflow";

export type User = {
  accounts?: Array<Account>;
  allowDynamicBooking: boolean | null;
  apiKeys?: Array<ApiKey>;
  availability?: Array<Availability>;
  avatar: string | null;
  away: boolean;
  bio: string | null;
  bookings?: Array<Booking>;
  brandColor: string;
  bufferTime: number;
  completedOnboarding: boolean;
  createdDate: Date;
  credentials?: Array<Credential>;
  darkBrandColor: string;
  defaultScheduleId: number | null;
  destinationCalendar?: DestinationCalendar | null;
  disableImpersonation: boolean;
  email: string;
  emailVerified: Date | null;
  endTime: number;
  eventTypes?: Array<EventType>;
  feedback?: Array<Feedback>;
  hideBranding: boolean;
  id: number;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId: string | null;
  impersonatedBy?: Array<Impersonation>;
  impersonatedUsers?: Array<Impersonation>;
  invitedTo: number | null;
  locale: string | null;
  metadata: JsonValue;
  name: string | null;
  password: string | null;
  plan?: "FREE" | "TRIAL" | "PRO";
  role?: "USER" | "ADMIN";
  schedules?: Array<Schedule>;
  selectedCalendars?: Array<SelectedCalendar>;
  sessions?: Array<Session>;
  startTime: number;
  teams?: Array<Membership>;
  theme: string | null;
  timeFormat: number | null;
  timeZone: string;
  trialEndsAt: Date | null;
  twoFactorEnabled: boolean;
  twoFactorSecret: string | null;
  username: string | null;
  verified: boolean | null;
  webhooks?: Array<Webhook>;
  weekStart: string;
  workflows?: Array<Workflow>;
};
