/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Attendee } from "./Attendee";
import { AttendeeCountArgs } from "./AttendeeCountArgs";
import { AttendeeFindManyArgs } from "./AttendeeFindManyArgs";
import { AttendeeFindUniqueArgs } from "./AttendeeFindUniqueArgs";
import { CreateAttendeeArgs } from "./CreateAttendeeArgs";
import { UpdateAttendeeArgs } from "./UpdateAttendeeArgs";
import { DeleteAttendeeArgs } from "./DeleteAttendeeArgs";
import { Booking } from "../../booking/base/Booking";
import { AttendeeService } from "../attendee.service";
@graphql.Resolver(() => Attendee)
export class AttendeeResolverBase {
  constructor(protected readonly service: AttendeeService) {}

  async _attendeesMeta(
    @graphql.Args() args: AttendeeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Attendee])
  async attendees(
    @graphql.Args() args: AttendeeFindManyArgs
  ): Promise<Attendee[]> {
    return this.service.attendees(args);
  }

  @graphql.Query(() => Attendee, { nullable: true })
  async attendee(
    @graphql.Args() args: AttendeeFindUniqueArgs
  ): Promise<Attendee | null> {
    const result = await this.service.attendee(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Attendee)
  async createAttendee(
    @graphql.Args() args: CreateAttendeeArgs
  ): Promise<Attendee> {
    return await this.service.createAttendee({
      ...args,
      data: {
        ...args.data,

        booking: args.data.booking
          ? {
              connect: args.data.booking,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Attendee)
  async updateAttendee(
    @graphql.Args() args: UpdateAttendeeArgs
  ): Promise<Attendee | null> {
    try {
      return await this.service.updateAttendee({
        ...args,
        data: {
          ...args.data,

          booking: args.data.booking
            ? {
                connect: args.data.booking,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Attendee)
  async deleteAttendee(
    @graphql.Args() args: DeleteAttendeeArgs
  ): Promise<Attendee | null> {
    try {
      return await this.service.deleteAttendee(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Booking, {
    nullable: true,
    name: "booking",
  })
  async getBooking(
    @graphql.Parent() parent: Attendee
  ): Promise<Booking | null> {
    const result = await this.service.getBooking(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
