/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AvailabilityListRelationFilter } from "../../availability/base/AvailabilityListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { EventTypeListRelationFilter } from "../../eventType/base/EventTypeListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ScheduleWhereInput {
  @ApiProperty({
    required: false,
    type: () => AvailabilityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AvailabilityListRelationFilter)
  @IsOptional()
  @Field(() => AvailabilityListRelationFilter, {
    nullable: true,
  })
  availability?: AvailabilityListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EventTypeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EventTypeListRelationFilter)
  @IsOptional()
  @Field(() => EventTypeListRelationFilter, {
    nullable: true,
  })
  eventType?: EventTypeListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  timeZone?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { ScheduleWhereInput as ScheduleWhereInput };
