/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsBoolean,
} from "class-validator";
import { EventTypeCreateNestedManyWithoutTeamsInput } from "./EventTypeCreateNestedManyWithoutTeamsInput";
import { Type } from "class-transformer";
import { MembershipCreateNestedManyWithoutTeamsInput } from "./MembershipCreateNestedManyWithoutTeamsInput";

@InputType()
class TeamCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: () => EventTypeCreateNestedManyWithoutTeamsInput,
  })
  @ValidateNested()
  @Type(() => EventTypeCreateNestedManyWithoutTeamsInput)
  @IsOptional()
  @Field(() => EventTypeCreateNestedManyWithoutTeamsInput, {
    nullable: true,
  })
  eventTypes?: EventTypeCreateNestedManyWithoutTeamsInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  hideBranding!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  logo?: string | null;

  @ApiProperty({
    required: false,
    type: () => MembershipCreateNestedManyWithoutTeamsInput,
  })
  @ValidateNested()
  @Type(() => MembershipCreateNestedManyWithoutTeamsInput)
  @IsOptional()
  @Field(() => MembershipCreateNestedManyWithoutTeamsInput, {
    nullable: true,
  })
  members?: MembershipCreateNestedManyWithoutTeamsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  slug?: string | null;
}

export { TeamCreateInput as TeamCreateInput };
